### ISSUE TITLE
Cannot update/use disenchanter after V14.10 (2.0.0) update

### ISSUE THREAD

**Issue by supermarth64** [marvinscham/disenchanter#187]
**Screenshot**
![Untitled](https://github.com/marvinscham/disenchanter/assets/3725394/5f435ad3-de12-415f-81e4-0c02420e27ca)

**Description (if necessary)**
- Had LOL patch 14.10 installed
- Had disenchanter v.1.8.0 installed, opened it up.
- Prompted for an update, I said yes.
- Update failed (didn't grab a screenshot here). Deleted both `disenchanter.exe` and `disenchanter_up.exe`.
- Downloaded a fresh copy of v2.0.0 from Github. Tried to run it, gave attached error. It gave the same error when failing the update.

**Version**
v2.0.0

**Comment by marvinscham** [comment]
@supermarth64 Thanks for taking the time to report! I've replaced the broken disenchanter.exe with a new one fixing this. You can download it from the [v2.0.0 page](https://github.com/marvinscham/disenchanter/releases/tag/v2.0.0) once again.

**Comment by marvinscham** [comment]
Docs in case someone has a similar problem:

Error was:
```bash
./disenchanter.exe
<internal:C:/Users/User/AppData/Local/Temp/ocr43B0.tmp/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/
setup (LoadError)
        from <internal:C:/Users/User/AppData/Local/Temp/ocr43B0.tmp/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
```

This happened because I used `bundle exec ocran` instead of just `ocran` to build the exe, which at some point seems to introduce an absolute reference to bundler's path on the build machine. This breaks the app unless you have bundler installed, which is why the error didn't occur when testing locally.
